name: Fermoy St. Patrick's Day Parade
favicon: null
layout_spectrum: 0.20033584255725145
typography_spectrum: 0.25988211343064904
title: Fermoy St. Patrick's Day Parade
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#191a14'
    - '#818284'
    - '#0ce05f'
    - '#eab48e'
  brandStrength: 0.555150342406705
  lightness: 0.34059323789551854
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
